version: "3.8"

services:
  api:
    build: .
    expose:
      - 8000
    ports:
    - 8000:8000
    restart: always
    environment:
      EPG_PATH: ${EPG_PATH}
      TMDB_API_KEY: ${TMDB_API_KEY}
      DEV_MODE: ${DEV_MODE}
      TZ: ${TZ}